BAH-2334| Added trigger job
Co-authored-by: Umair Fayaz <omayrfayaz@gmail.com>

diff --git a/.github/workflows/build_publish.yaml b/.github/workflows/build_publish.yaml
--- a/.github/workflows/build_publish.yaml
+++ b/.github/workflows/build_publish.yaml
@@ -24,6 +24,26 @@ jobs:
       - name: Upload bahmniOfflineSync as Artifact
         uses: actions/upload-artifact@v2
         with:
-          name: bahmni-offline-sync
+          name: bahmni-offline-sync-omod
           path: | 
             omod/target/bahmniOfflineSync.omod
+    
+  trigger-dependent-repos:
+    name: Trigger Workflows
+    runs-on: ubuntu-latest
+    needs: build-bahmni-offlinesync
+    steps:
+      - name: Create repository_dispatch
+        env:
+          REPOSITORY_NAME: bahmni-offline
+          ORG_NAME: Bahmni
+          EVENT_TYPE: bahmni-offline-sync-trigger
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi  
